version: '3.0'
services:

  test-search-api:
    build: ./search-api
    ports:
      - "3000:3000"
    restart: always

  test-provider-01:
    build: ./search-api-data-provider
    ports:
      - "3001:3000"
    volumes:
      - ./test/db1.json:/home/node/app/data/db.json
      - ./test/provider_datasource.json:/home/node/app/server/datasources.json
    restart: always

  test-provider-02:
    build: ./search-api-data-provider
    ports:
      - "3002:3000"
    volumes:
      - ./test/db2.json:/home/node/app/data/db.json
      - ./test/provider_datasource.json:/home/node/app/server/datasources.json
    restart: always
