name: PaNOSC Federated Search API CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: |
          cd test
          docker-compose -f docker-compose-local-data-provider-testCI docker compo.ci.yaml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs test-search-api
      - name: Check PaNOSC federated search configuration
        run: docker exec test_search-api wget "http://localhost:3000"
      - name: Run test suite
        run: echo "Tests are fine!!! Everything is fine!!!"
